import {describe,expect,it} from "vitest";
import type {ExportArtifact} from "@visual-architecture/exporter";
import {hashBytes} from "@visual-architecture/exporter";
import {deliverAtomic,MemoryDeliveryStore,specificationHash,type DeliveryStore} from "../src/index";
const make=(text:string):ExportArtifact=>{const bytes=new TextEncoder().encode(text);return{format:"html",mimeType:"text/html",bytes,hash:hashBytes(bytes),geometryHash:"geo"}};
const active=async(s:MemoryDeliveryStore)=>s.readGood("preview");
describe("G9 atomic delivery",()=>{
 it("qualifies VALID V1 -> INVALID V2 -> V1 PRESERVED -> VALID V3",async()=>{const s=new MemoryDeliveryStore(),v1=make("<!doctype html><svg><title>v1</title></svg>"),bad=make("broken"),v3=make("<!doctype html><svg><title>v3</title></svg>");const r1=await deliverAtomic("preview",{v:1},v1,s);const v1bytes=[...(await active(s))!.bytes];expect(r1.accepted).toBe(true);const r2=await deliverAtomic("preview",{v:2},bad,s);expect(r2.accepted).toBe(false);expect((await active(s))!.hash).toBe(v1.hash);expect([...(await active(s))!.bytes]).toEqual(v1bytes);expect(s.candidate.size).toBe(0);const r3=await deliverAtomic("preview",{v:3},v3,s);expect(r3.accepted).toBe(true);expect((await active(s))!.hash).toBe(v3.hash);expect(r3.artifactHash).toBe(v3.hash);expect(s.candidate.size).toBe(0)});
 it("preserves good artifact when verification returns failure or throws",async()=>{for(const verify of [async()=>["BROWSER_VERIFY_FAILED"],async()=>{throw new Error("browser crashed")}]){const s=new MemoryDeliveryStore(),v1=make("<!doctype html><svg></svg>"),v2=make("<!doctype html><svg><title>v2</title></svg>");await deliverAtomic("preview",{v:1},v1,s);const r=await deliverAtomic("preview",{v:2},v2,s,verify);expect(r.accepted).toBe(false);expect((await active(s))!.hash).toBe(v1.hash);expect(s.candidate.size).toBe(0)}});
 it("rejects malformed, partial and hash-mismatched candidates",async()=>{const s=new MemoryDeliveryStore(),v1=make("<!doctype html><svg></svg>");await deliverAtomic("preview",{v:1},v1,s);for(const bad of [make("broken"),{...make("<!doctype html><svg></svg>"),bytes:new Uint8Array()},{...make("<!doctype html><svg><title>x</title></svg>"),hash:"00000000"}]){const r=await deliverAtomic("preview",{bad:true},bad,s);expect(r.accepted).toBe(false);expect((await active(s))!.hash).toBe(v1.hash);expect(s.candidate.size).toBe(0)}});
 it("detects staged candidate tampering before promotion",async()=>{const s=new MemoryDeliveryStore(),v1=make("<!doctype html><svg></svg>"),v2=make("<!doctype html><svg><title>v2</title></svg>");await deliverAtomic("preview",{v:1},v1,s);const original=s.readCandidate.bind(s);let reads=0;s.readCandidate=async k=>{const a=await original(k);reads++;return reads>1&&a?{...a,bytes:new TextEncoder().encode("<!doctype html><svg><title>tampered</title></svg>")}:a};const r=await deliverAtomic("preview",{v:2},v2,s);expect(r.accepted).toBe(false);expect(r.errors.join(" ")).toMatch(/INTEGRITY|HASH/);expect((await active(s))!.hash).toBe(v1.hash)});
 it("handles missing candidate and promotion failure without losing V1",async()=>{for(const mode of ["missing","promotion"]){const s=new MemoryDeliveryStore(),v1=make("<!doctype html><svg></svg>"),v2=make("<!doctype html><svg><title>v2</title></svg>");await deliverAtomic("preview",{v:1},v1,s);if(mode==="missing")s.readCandidate=async()=>undefined;else s.promoteCandidate=async()=>{throw new Error("disk rename failed")};const r=await deliverAtomic("preview",{v:2},v2,s);expect(r.accepted).toBe(false);expect((await active(s))!.hash).toBe(v1.hash);expect(s.candidate.size).toBe(0)}});
 it("reports destination write failure without touching active artifact",async()=>{const s=new MemoryDeliveryStore(),v1=make("<!doctype html><svg></svg>"),v2=make("<!doctype html><svg><title>v2</title></svg>");await deliverAtomic("preview",{v:1},v1,s);s.writeCandidate=async()=>{throw new Error("disk full")};const r=await deliverAtomic("preview",{v:2},v2,s);expect(r.accepted).toBe(false);expect(r.errors[0]).toContain("CANDIDATE_WRITE_ERROR");expect((await active(s))!.hash).toBe(v1.hash)});
 it("surfaces cleanup failure while preserving V1",async()=>{const base=new MemoryDeliveryStore(),v1=make("<!doctype html><svg></svg>"),bad=make("broken");await deliverAtomic("preview",{v:1},v1,base);const store:DeliveryStore={readGood:k=>base.readGood(k),writeCandidate:(k,a)=>base.writeCandidate(k,a),readCandidate:k=>base.readCandidate(k),promoteCandidate:k=>base.promoteCandidate(k),discardCandidate:async()=>{base.candidate.clear();throw new Error("cleanup failed")}};const r=await deliverAtomic("preview",{v:2},bad,store);expect(r.accepted).toBe(false);expect(r.errors.join(" ")).toContain("CLEANUP_ERROR");expect((await base.readGood("preview"))!.hash).toBe(v1.hash);expect(base.candidate.size).toBe(0)});
 it("specification hashing is canonical and meaningful changes differ",()=>{expect(specificationHash({a:1,b:{y:2,x:3}})).toBe(specificationHash({b:{x:3,y:2},a:1}));expect(specificationHash({a:1})).not.toBe(specificationHash({a:2}))});
});
