import {describe,expect,it} from "vitest";import type {DiagramIR,DiagramKind} from "@visual-architecture/ir";import {semanticEngines,validateSemantics} from "../src/index";
const base=(kind:DiagramKind):DiagramIR=>({version:"1.0",kind,document:{title:kind},nodes:[],relationships:[],boundaries:[],evidence:[],presentation:{}});
describe("five independent semantic engines",()=>{
 it("registers exactly five engines",()=>expect(Object.keys(semanticEngines).sort()).toEqual(["architecture","data-flow","lifecycle","sequence","workflow"]));
 it("architecture validates roles and nested boundary references",()=>{const ir=base("architecture");ir.nodes=[{id:"api",type:"service",label:"API"}];ir.boundaries=[{id:"outer",type:"trust",label:"Outer",boundaryIds:["missing"]}];const d=validateSemantics(ir);expect(d.some(x=>x.code==="BOUNDARY_NESTING_INVALID")).toBe(true)});
 it("workflow requires exactly one start, an end and main path",()=>{const ir=base("workflow");ir.nodes=[{id:"s",type:"start",label:"S"},{id:"x",type:"step",label:"X"},{id:"e",type:"end",label:"E"}];ir.relationships=[{id:"r",source:"s",target:"x",type:"flow"}];expect(validateSemantics(ir).some(d=>d.code==="WORKFLOW_MAIN_PATH_MISSING")).toBe(true)});
 it("sequence enforces participant and temporal ordering",()=>{const ir=base("sequence");ir.nodes=[{id:"a",type:"participant",label:"A"},{id:"b",type:"participant",label:"B"}];ir.relationships=[{id:"m1",source:"a",target:"b",type:"message",metadata:{order:2}},{id:"m2",source:"b",target:"a",type:"reply",metadata:{order:1}}];expect(validateSemantics(ir).some(d=>d.code==="SEQUENCE_ORDER_INVALID")).toBe(true)});
 it("data flow requires source/destination and flow edges",()=>{const ir=base("data-flow");ir.nodes=[{id:"a",type:"source",label:"A"},{id:"b",type:"destination",label:"B"}];ir.relationships=[{id:"r",source:"a",target:"b",type:"calls"}];expect(validateSemantics(ir).some(d=>d.code==="DATA_FLOW_RELATION_TYPE_INVALID")).toBe(true)});
 it("lifecycle rejects outgoing edges from terminal states",()=>{const ir=base("lifecycle");ir.nodes=[{id:"start",type:"state",label:"Start",metadata:{state:"START"}},{id:"done",type:"state",label:"Done",metadata:{state:"COMPLETED"}}];ir.relationships=[{id:"bad",source:"done",target:"start",type:"transition"}];expect(validateSemantics(ir).some(d=>d.code==="LIFECYCLE_TERMINAL_OUTGOING")).toBe(true)});
});
describe("G3 positive semantic fixtures",()=>{
 it("accepts architecture stores, externals and nested trust boundaries",()=>{const ir=base("architecture");ir.nodes=[{id:"api",type:"service",label:"API"},{id:"db",type:"store",label:"DB"},{id:"ext",type:"external",label:"External"}];ir.relationships=[{id:"api-db",source:"api",target:"db",type:"writes"}];ir.boundaries=[{id:"inner",type:"trust",label:"Inner",nodeIds:["api","db"]},{id:"outer",type:"group",label:"Outer",boundaryIds:["inner"],nodeIds:["ext"]}];expect(validateSemantics(ir).filter(d=>d.severity==="error")).toEqual([])});
 it("accepts workflow lanes/phases/groups with a marked main path",()=>{const ir=base("workflow");ir.nodes=[{id:"start",type:"start",label:"Start"},{id:"lane",type:"lane",label:"Ops"},{id:"phase",type:"phase",label:"Review"},{id:"approval",type:"approval",label:"Approve"},{id:"end",type:"end",label:"End"}];ir.relationships=[{id:"a",source:"start",target:"approval",type:"flow",metadata:{mainPath:true}},{id:"b",source:"approval",target:"end",type:"flow",metadata:{mainPath:true}}];expect(validateSemantics(ir).filter(d=>d.severity==="error")).toEqual([])});
 it("accepts ordered sequence messages and bounded activations",()=>{const ir=base("sequence");ir.nodes=[{id:"client",type:"participant",label:"Client",metadata:{activationStart:1,activationEnd:2}},{id:"api",type:"participant",label:"API"}];ir.relationships=[{id:"m1",source:"client",target:"api",type:"message",metadata:{order:1}},{id:"m2",source:"api",target:"client",type:"reply",metadata:{order:2}}];expect(validateSemantics(ir).filter(d=>d.severity==="error")).toEqual([])});
 it("accepts staged data lineage",()=>{const ir=base("data-flow");ir.nodes=[{id:"src",type:"source",label:"Source"},{id:"stage",type:"stage",label:"Stage"},{id:"proc",type:"processor",label:"Process"},{id:"store",type:"store",label:"Store"},{id:"dest",type:"destination",label:"Destination"}];ir.relationships=[["a","src","stage"],["b","stage","proc"],["c","proc","store"],["d","store","dest"]].map(([id,source,target])=>({id:id!,source:source!,target:target!,type:"flow"}));expect(validateSemantics(ir).filter(d=>d.severity==="error")).toEqual([])});
 it("accepts waits/retries before terminal lifecycle completion",()=>{const ir=base("lifecycle");ir.nodes=["START","ACTIVE","WAITING","RETRYING","COMPLETED"].map(s=>({id:s.toLowerCase(),type:"state",label:s,metadata:{state:s}}));ir.relationships=[["a","start","active"],["b","active","waiting"],["c","waiting","retrying"],["d","retrying","active"],["e","active","completed"]].map(([id,source,target])=>({id:id!,source:source!,target:target!,type:"transition"}));expect(validateSemantics(ir).filter(d=>d.severity==="error")).toEqual([])});
});
