import {describe,expect,it} from "vitest";import {assertClassification,canonicalEvidence,evidenceFromFinding,validatePinnedEvidence,verifyEvidenceAgainstContent} from "../src/index";
const hash=(s:string)=>"h:"+s;
describe("revision-pinned evidence",()=>{
 it("preserves source identity and relationship identity",()=>{const e=evidenceFromFinding({id:"a",kind:"relationship",label:"API uses DB",classification:"VERIFIED",confidence:1,source:{repository:"o/r",commitSha:"abc",file:"src/api.ts",lineStart:1,lineEnd:2,blobSha:"blob",contentHash:"hash"}},"api","api-db");expect(validatePinnedEvidence(e)).toEqual([]);expect(e.relationshipId).toBe("api-db")});
 it("rejects unpinned/invalid evidence",()=>{expect(validatePinnedEvidence({id:"x",classification:"VERIFIED"}).length).toBeGreaterThan(0);expect(validatePinnedEvidence({id:"x",classification:"INFERRED",repository:"r",commitSha:"c",file:"f",blobSha:"b",contentHash:"h",lineStart:2,lineEnd:1,confidence:2})).toEqual(expect.arrayContaining(["EVIDENCE_RANGE_INVALID","EVIDENCE_CONFIDENCE_INVALID"]))});
 it("keeps classifications distinct",()=>{expect(assertClassification("INFERRED")).toBe("INFERRED");expect(assertClassification("VERIFIED")).toBe("VERIFIED");expect(assertClassification("bogus")).toBe("UNKNOWN")});
 it("validates exact line ranges and detects content tampering",()=>{const content="first\r\nनमस्ते\r\nlast";const e={id:"e",classification:"VERIFIED" as const,repository:"r",commitSha:"c",file:"f",blobSha:"b",contentHash:hash(content),lineStart:2,lineEnd:2,excerpt:"नमस्ते"};expect(verifyEvidenceAgainstContent(e,content,hash)).toEqual([]);expect(verifyEvidenceAgainstContent(e,content+"!",hash)).toContain("EVIDENCE_CONTENT_HASH_MISMATCH")});
 it("canonicalizes multiple evidence items deterministically",()=>{const a={id:"b",classification:"UNKNOWN" as const,repository:"r",commitSha:"c",file:"z",lineStart:2},b={id:"a",classification:"USER_SUPPLIED" as const,repository:"r",commitSha:"c",file:"a",lineStart:1};expect(canonicalEvidence([a,b]).map(x=>x.id)).toEqual(["a","b"])});
});
