import type {DiagramIR,DiagramKind,DiagramNode,DiagramRelationship} from "@visual-architecture/ir";
import type {LayoutResult,NodeGeometry,ContainerGeometry,EdgeGeometry} from "@visual-architecture/layout";

export interface RenderResult{kind:DiagramKind;svg:string;geometryHash:string}
type Renderer=(ir:DiagramIR,layout:LayoutResult)=>RenderResult;
type Shape="rect"|"round"|"pill"|"diamond"|"store"|"external"|"state"|"terminal"|"source"|"destination"|"processor";
const esc=(v:unknown)=>String(v??"").replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F]/g,"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#39;");
const sid=(v:string)=>esc(v);
const attrs=(x:Record<string,unknown>)=>Object.entries(x).filter(([,v])=>v!==undefined).map(([k,v])=>` ${k}="${esc(v)}"`).join("");
const lines=(g:NodeGeometry,label:string)=>g.labelLines?.length?g.labelLines:[label];
const text=(x:number,y:number,ls:string[],role:string,anchor="middle")=>`<text${attrs({"data-text-role":role,x,y,"text-anchor":anchor,"aria-label":ls.join(" ")})}>${ls.map((l,i)=>`<tspan x="${x}" dy="${i?18:0}">${esc(l)}</tspan>`).join("")}</text>`;
const shape=(g:NodeGeometry,n:DiagramNode,s:Shape,model:string)=>{const common=attrs({id:`node-${n.id}`,"data-node-id":n.id,"data-semantic-role":n.type,"data-model":model,"data-shape":s,role:"group","aria-label":n.label,tabindex:"-1"});let body="";if(s==="diamond"){const cx=g.x+g.width/2,cy=g.y+g.height/2;body=`<polygon points="${cx},${g.y} ${g.x+g.width},${cy} ${cx},${g.y+g.height} ${g.x},${cy}"/>`}else if(s==="store"){body=`<rect x="${g.x}" y="${g.y+8}" width="${g.width}" height="${g.height-16}" rx="8"/><ellipse cx="${g.x+g.width/2}" cy="${g.y+8}" rx="${g.width/2}" ry="8"/><path d="M${g.x} ${g.y+g.height-8} A${g.width/2} 8 0 0 0 ${g.x+g.width} ${g.y+g.height-8}"/>`}else if(s==="external"){body=`<rect x="${g.x}" y="${g.y}" width="${g.width}" height="${g.height}" rx="4"/><path d="M${g.x+10} ${g.y+10}h14v14 M${g.x+24} ${g.y+10}l-16 16"/>`}else if(s==="source"||s==="destination"){const d=s==="source"?`M${g.x} ${g.y}h${g.width-18}l18 ${g.height/2}l-18 ${g.height/2}h-${g.width-18}z`:`M${g.x+18} ${g.y}h${g.width-18}v${g.height}h-${g.width-18}l-18 -${g.height/2}z`;body=`<path d="${d}"/>`}else{const rx=s==="pill"?g.height/2:s==="round"||s==="state"||s==="terminal"||s==="processor"?14:4;body=`<rect x="${g.x}" y="${g.y}" width="${g.width}" height="${g.height}" rx="${rx}"/>${s==="terminal"?`<rect x="${g.x+5}" y="${g.y+5}" width="${g.width-10}" height="${g.height-10}" rx="${Math.max(4,rx-4)}" class="terminal-inner"/>`:""}`}const ls=lines(g,n.label),ty=g.y+g.height/2-(ls.length-1)*9;return`<g${common}>${body}${text(g.x+g.width/2,ty,ls,"node-label")}</g>`};
const container=(g:ContainerGeometry,semantic:string,extra:Record<string,unknown>={})=>`<g${attrs({id:`${semantic}-${g.id}`,[`data-${semantic}-id`]:g.id,"data-container-kind":g.kind,"data-depth":g.depth,role:"group","aria-label":g.label,...extra})}><rect x="${g.x}" y="${g.y}" width="${g.width}" height="${g.height}" rx="10"/>${text(g.x+12,g.y+22,[g.label],`${semantic}-heading`,"start")}</g>`;
const relation=(g:EdgeGeometry,r:DiagramRelationship,model:string,extra:Record<string,unknown>={})=>{const pts=g.points.map(p=>`${p.x},${p.y}`).join(" ");const label=g.label??r.label;const lb=g.labelBox;return`<g${attrs({id:`relation-${r.id}`,"data-relation-id":r.id,"data-relation-kind":r.type,"data-source":r.source,"data-target":r.target,"data-model":model,role:"group","aria-label":label??`${r.source} to ${r.target}`,...extra})}><polyline points="${pts}" fill="none" marker-end="url(#arrow)"/>${label&&lb?text(lb.x+lb.width/2,lb.y+14,[label],"relationship-label"):label&&g.points.length?text((g.points[0]!.x+g.points.at(-1)!.x)/2,(g.points[0]!.y+g.points.at(-1)!.y)/2-8,[label],"relationship-label"):""}</g>`};
const styles=`<style>:root{--va-bg:#fff;--va-fg:#172033;--va-muted:#667085;--va-line:#475467;--va-surface:#f8fafc;--va-accent:#344054}svg{background:var(--va-bg);color:var(--va-fg);font:14px system-ui,sans-serif}g[data-node-id]>rect,g[data-node-id]>path,g[data-node-id]>polygon,g[data-node-id]>ellipse{fill:var(--va-surface);stroke:var(--va-fg);stroke-width:1.5}text{fill:var(--va-fg)}polyline{stroke:var(--va-line);stroke-width:1.6}.container>rect,[data-container-kind]>rect{fill:none;stroke:var(--va-muted);stroke-width:1.2}.trust>rect,[data-boundary-type="trust"]>rect{stroke-dasharray:8 5;stroke-width:2}.external>rect{stroke-dasharray:5 4}.main-path polyline{stroke-width:3}.main-path polyline+text{text-decoration:underline}.lifeline{stroke:var(--va-muted);stroke-dasharray:5 5}.activation{fill:var(--va-surface);stroke:var(--va-fg)}.segment>rect{fill:none;stroke:var(--va-muted);stroke-dasharray:7 4}.terminal-inner{fill:none!important}.preset-signal polyline{stroke-width:2.2}.preset-blueprint{font-family:ui-monospace,monospace}.preset-editorial{font-family:Georgia,serif}.theme-dark{--va-bg:#101828;--va-fg:#f2f4f7;--va-muted:#98a2b3;--va-line:#d0d5dd;--va-surface:#1d2939}</style>`;
const frame=(ir:DiagramIR,l:LayoutResult,body:string)=>{const preset=ir.presentation.preset??"classic",theme=ir.presentation.theme??"light";return`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${l.width} ${l.height}" role="img" aria-labelledby="diagram-title diagram-desc" class="preset-${esc(preset)} theme-${esc(theme)}" data-preset="${esc(preset)}" data-theme="${esc(theme)}" data-diagram-kind="${ir.kind}" data-geometry-hash="${l.geometryHash}"><title id="diagram-title">${esc(ir.document.title)}</title><desc id="diagram-desc">${esc(ir.document.description??`${ir.kind} diagram`)}</desc><defs><marker id="arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8 Z" fill="context-stroke"/></marker></defs>${styles}${body}</svg>`};
const legend=(l:LayoutResult)=>l.legend?`<g id="legend" data-semantic-role="legend" role="group" aria-label="Legend"><rect x="${l.legend.x}" y="${l.legend.y}" width="${l.legend.width}" height="${l.legend.height}" rx="8"/>${l.legend.items.map((v,i)=>text(l.legend!.x+12,l.legend!.y+24+i*20,[v],"legend-item","start")).join("")}</g>`:"";
const maps=(ir:DiagramIR,l:LayoutResult)=>({nodes:new Map(ir.nodes.map(n=>[n.id,n])),rels:new Map(ir.relationships.map(r=>[r.id,r])),geom:new Map(l.nodes.map(n=>[n.id,n]))});
const boundaries=(ir:DiagramIR,l:LayoutResult)=>l.containers.filter(c=>c.kind==="boundary").map(c=>{const b=ir.boundaries.find(x=>x.id===c.id);const type=b?.type??"boundary";return container(c,type==="group"?"group":"boundary",{"data-boundary-type":type,class:type.includes("trust")?"trust container":"container"})}).join("");
const edges=(ir:DiagramIR,l:LayoutResult,model:string,decorate=(r:DiagramRelationship)=>({}))=>{const rm=new Map(ir.relationships.map(r=>[r.id,r]));return l.edges.map(e=>rm.get(e.id)?relation(e,rm.get(e.id)!,model,decorate(rm.get(e.id)!)):"").join("")};

export const architectureRenderer:Renderer=(ir,l)=>{const m=maps(ir,l);const body=boundaries(ir,l)+edges(ir,l,"architecture")+l.nodes.map(g=>{const n=m.nodes.get(g.id)!;const t=n.type;const s:Shape=["store","database"].includes(t)?"store":t==="external"?"external":"round";return shape(g,n,s,"architecture")}).join("")+legend(l);return{kind:ir.kind,svg:frame(ir,l,body),geometryHash:l.geometryHash}};
export const workflowRenderer:Renderer=(ir,l)=>{const m=maps(ir,l);const cs=l.containers.filter(c=>c.kind==="lane"||c.kind==="phase").map(c=>container(c,c.kind,{"data-workflow-container":c.kind,class:`container ${c.kind}`})).join("");const rs=edges(ir,l,"workflow",r=>({"data-main-path":r.metadata?.mainPath===true?"true":"false",class:r.metadata?.mainPath===true?"main-path":"secondary-path"}));const ns=l.nodes.map(g=>{const n=m.nodes.get(g.id)!;const s:Shape=n.type==="decision"?"diamond":n.type==="start"||n.type==="end"?"pill":"round";return shape(g,n,s,"workflow")}).join("");return{kind:ir.kind,svg:frame(ir,l,cs+boundaries(ir,l)+rs+ns+legend(l)),geometryHash:l.geometryHash}};
export const sequenceRenderer:Renderer=(ir,l)=>{const m=maps(ir,l);const headerBottom=Math.max(...l.nodes.map(n=>n.y+n.height),0);const eventBottom=Math.max(headerBottom,...l.edges.flatMap(e=>e.points.map(p=>p.y)),...l.containers.map(c=>c.y+c.height));const segments=l.containers.filter(c=>c.kind==="segment"&&c.id.startsWith("segment:")).map(c=>container(c,"segment",{class:"segment"})).join("");const activations=l.containers.filter(c=>c.kind==="segment"&&c.id.startsWith("activation:")).map(c=>`<rect${attrs({id:`activation-${c.id.slice(11)}`,"data-activation-id":c.id.slice(11),class:"activation",x:c.x,y:c.y,width:c.width,height:c.height,role:"img","aria-label":c.label})}/>`).join("");const participants=l.nodes.map(g=>{const n=m.nodes.get(g.id)!;return shape(g,n,"pill","sequence")+`<line${attrs({id:`lifeline-${n.id}`,"data-lifeline-id":n.id,class:"lifeline",x1:g.x+g.width/2,y1:g.y+g.height,x2:g.x+g.width/2,y2:eventBottom+24})}/>`}).join("");const messages=edges(ir,l,"sequence",r=>({"data-message-id":r.id,"data-message-order":r.metadata?.order??"",class:"message"}));return{kind:ir.kind,svg:frame(ir,l,segments+participants+messages+activations+legend(l)),geometryHash:l.geometryHash}};
export const dataFlowRenderer:Renderer=(ir,l)=>{const m=maps(ir,l);const stages=l.containers.filter(c=>c.kind==="boundary"||c.kind==="phase").map(c=>container(c,c.kind==="phase"?"stage":"boundary",{"data-dataflow-container":"true",class:"container"})).join("");const ns=l.nodes.map(g=>{const n=m.nodes.get(g.id)!;const s:Shape=n.type==="source"?"source":n.type==="destination"?"destination":n.type==="store"?"store":n.type==="process"||n.type==="processor"?"processor":"round";return shape(g,n,s,"data-flow")}).join("");return{kind:ir.kind,svg:frame(ir,l,stages+edges(ir,l,"data-flow",r=>({"data-flow-id":r.id,class:"data-flow"}))+ns+legend(l)),geometryHash:l.geometryHash}};
export const lifecycleRenderer:Renderer=(ir,l)=>{const m=maps(ir,l);const lanes=l.containers.filter(c=>c.kind==="lane").map(c=>container(c,"lane",{"data-lifecycle-lane":"true",class:"container lane"})).join("");const terminal=new Set(["FAILED","CANCELLED","COMPLETED"]);const ns=l.nodes.map(g=>{const n=m.nodes.get(g.id)!;const state=String(n.metadata?.state??n.label).toUpperCase();const s:Shape=terminal.has(state)?"terminal":state==="START"?"pill":"state";return shape(g,n,s,"lifecycle").replace("<g ",`<g data-state="${esc(state)}" data-terminal="${terminal.has(state)}" `)}).join("");return{kind:ir.kind,svg:frame(ir,l,lanes+edges(ir,l,"lifecycle",r=>({"data-transition-id":r.id,"data-self-loop":r.source===r.target?"true":"false",class:r.source===r.target?"retry-transition":"transition"}))+ns+legend(l)),geometryHash:l.geometryHash}};

export const renderers:Record<DiagramKind,Renderer>={architecture:architectureRenderer,workflow:workflowRenderer,sequence:sequenceRenderer,"data-flow":dataFlowRenderer,lifecycle:lifecycleRenderer};
export function renderDiagram(ir:DiagramIR,layout:LayoutResult):RenderResult{return renderers[ir.kind](ir,layout)}
export function validateRenderResult(result:RenderResult,kind:DiagramKind,hash:string):string[]{const e=validateSvg(result.svg);if(result.kind!==kind)e.push("SVG_KIND_MISMATCH");if(result.geometryHash!==hash)e.push("SVG_GEOMETRY_HASH_MISMATCH");if(!result.svg.includes(`data-diagram-kind="${kind}"`))e.push("SVG_KIND_METADATA_MISSING");if(!result.svg.includes(`data-geometry-hash="${hash}"`))e.push("SVG_GEOMETRY_METADATA_MISSING");return e}
export function validateSvg(svg:string):string[]{const e:string[]=[];if(!svg.startsWith("<svg")||!svg.endsWith("</svg>"))e.push("SVG_ROOT_INVALID");if(/<script\b/i.test(svg))e.push("SVG_SCRIPT_FORBIDDEN");if(/<foreignObject\b/i.test(svg))e.push("SVG_FOREIGN_CONTENT_FORBIDDEN");if(/<[^>]*\son[a-z]+\s*=/i.test(svg))e.push("SVG_EVENT_HANDLER_FORBIDDEN");if(/(?:href|src)\s*=\s*["']\s*javascript:/i.test(svg))e.push("SVG_UNSAFE_URL");if(/<(?:iframe|object|embed|audio|video|canvas)\b/i.test(svg))e.push("SVG_FOREIGN_CONTENT_FORBIDDEN");return e}
