import {describe,expect,it} from "vitest";import type {DiagramIR} from "@visual-architecture/ir";import {DEFAULT_LAYOUT_CONFIG,layoutDiagram} from "../src/index";
const base=(kind:DiagramIR["kind"]):DiagramIR=>({version:"1.0",kind,document:{title:"G4"},nodes:[],relationships:[],boundaries:[],evidence:[],presentation:{}});
const finite=(r:ReturnType<typeof layoutDiagram>)=>{expect(r.nodes.every(n=>Number.isFinite(n.x+n.y+n.width+n.height)&&n.width>0&&n.height>0)).toBe(true);expect(r.edges.every(e=>e.points.length>=2&&e.points.every(p=>Number.isFinite(p.x+p.y)))).toBe(true);for(const n of r.nodes){expect(n.x+n.width).toBeLessThanOrEqual(r.bounds.width);expect(n.y+n.height).toBeLessThanOrEqual(r.bounds.height)}};
describe("G4 production deterministic layout",()=>{
 it("is deterministic across repeats and authored order",()=>{const ir=base("architecture");ir.nodes=[{id:"z",type:"service",label:"Z"},{id:"a",type:"store",label:"A"}];ir.relationships=[{id:"r",source:"z",target:"a",type:"calls"}];const h=layoutDiagram(ir).geometryHash;for(let i=0;i<20;i++)expect(layoutDiagram({...ir,nodes:[...ir.nodes].reverse()}).geometryHash).toBe(h)});
 it("changes hash when authoritative geometry changes",()=>{const ir=base("architecture");ir.nodes=[{id:"a",type:"service",label:"A"}];expect(layoutDiagram(ir).geometryHash).not.toBe(layoutDiagram(ir,{nodeGapX:DEFAULT_LAYOUT_CONFIG.nodeGapX+1}).geometryHash)});
 it("contains nested architecture boundaries including long Unicode headings",()=>{const ir=base("architecture");ir.nodes=[{id:"api",type:"service",label:"प्रमाणीकरण API 認証サービス"},{id:"db",type:"store",label:"डेटाबेस 数据库"}];ir.boundaries=[{id:"inner",type:"trust",label:"विश्वास सीमा 信頼境界",nodeIds:["api","db"]},{id:"outer",type:"group",label:"बाहरी समूह 外部グループ",boundaryIds:["inner"]}];const r=layoutDiagram(ir);finite(r);expect(r.containers).toHaveLength(2);const inner=r.containers.find(x=>x.id==="inner")!,outer=r.containers.find(x=>x.id==="outer")!;expect(inner.x).toBeGreaterThanOrEqual(outer.x);expect(inner.x+inner.width).toBeLessThanOrEqual(outer.x+outer.width);expect(r.diagnostics).toEqual([])});
 it("handles empty, sibling and deep boundaries",()=>{const ir=base("architecture");ir.nodes=[{id:"n",type:"component",label:"n"}];ir.boundaries=[{id:"a",type:"group",label:"A",nodeIds:["n"]},{id:"b",type:"group",label:"B"},{id:"c",type:"group",label:"C",boundaryIds:["a"]},{id:"d",type:"group",label:"D",boundaryIds:["c"]}];const r=layoutDiagram(ir);finite(r);expect(r.containers).toHaveLength(4)});
 it("preserves sequence temporal message order",()=>{const ir=base("sequence");ir.nodes=[{id:"b",type:"participant",label:"B",metadata:{order:2}},{id:"a",type:"participant",label:"A",metadata:{order:1}}];ir.relationships=[{id:"m2",source:"b",target:"a",type:"message",metadata:{order:2}},{id:"m1",source:"a",target:"b",type:"message",metadata:{order:1}}];const r=layoutDiagram(ir);expect(r.edges.find(e=>e.id==="m2")!.points[0]!.y).toBeGreaterThan(r.edges.find(e=>e.id==="m1")!.points[0]!.y)});
 it("lays out workflow, data flow and lifecycle directionally",()=>{for(const kind of ["workflow","data-flow","lifecycle"] as const){const ir=base(kind);ir.nodes=[{id:"start",type:kind==="lifecycle"?"state":"start",label:kind==="lifecycle"?"START":"Start",metadata:kind==="lifecycle"?{state:"START"}:{}},{id:"mid",type:kind==="data-flow"?"processor":kind==="lifecycle"?"state":"task",label:"Middle",metadata:kind==="lifecycle"?{state:"ACTIVE"}:{}},{id:"end",type:kind==="data-flow"?"destination":kind==="lifecycle"?"state":"end",label:kind==="lifecycle"?"COMPLETED":"End",metadata:kind==="lifecycle"?{state:"COMPLETED"}:{}}];ir.relationships=[{id:"a",source:"start",target:"mid",type:kind==="lifecycle"?"transition":"flow"},{id:"b",source:"mid",target:"end",type:kind==="lifecycle"?"transition":"flow"}];const r=layoutDiagram(ir);finite(r);expect(r.nodes.find(n=>n.id==="end")!.x).toBeGreaterThan(r.nodes.find(n=>n.id==="start")!.x)}});
 it("supports self-loops, reciprocal edges and cycles without malformed coordinates",()=>{const ir=base("lifecycle");ir.nodes=[{id:"a",type:"state",label:"ACTIVE",metadata:{state:"ACTIVE"}},{id:"b",type:"state",label:"RETRYING",metadata:{state:"RETRYING"}}];ir.relationships=[{id:"self",source:"a",target:"a",type:"transition"},{id:"ab",source:"a",target:"b",type:"transition"},{id:"ba",source:"b",target:"a",type:"transition"}];const r=layoutDiagram(ir);finite(r);expect(r.edges.find(e=>e.id==="self")!.points.length).toBeGreaterThan(4)});
 it("keeps long multilingual labels inside conservatively sized nodes",()=>{const ir=base("data-flow");ir.nodes=[{id:"u",type:"processor",label:"Authentication प्रमाणीकरण प्रमाणीकरण 数据处理 認証 procesamiento técnico muy largo"}];const n=layoutDiagram(ir).nodes[0]!;expect(n.labelLines.length).toBeGreaterThan(1);expect(n.height).toBeGreaterThanOrEqual(DEFAULT_LAYOUT_CONFIG.nodeHeight)});
 it("places legend outside diagram content and includes it in bounds",()=>{const ir=base("architecture");ir.nodes=[{id:"a",type:"service",label:"A"},{id:"b",type:"store",label:"B"}];const r=layoutDiagram(ir);expect(r.legend).toBeDefined();expect(r.legend!.y+r.legend!.height).toBeLessThanOrEqual(r.bounds.height);expect(r.nodes.every(n=>n.y+n.height<=r.legend!.y)).toBe(true)});
 it("handles 100 nodes and several hundred relationships deterministically",()=>{const ir=base("architecture");ir.nodes=Array.from({length:100},(_,i)=>({id:`n-${String(i).padStart(3,"0")}`,type:i%7===0?"store":"component",label:`Node ${i} 数据`}));ir.relationships=Array.from({length:400},(_,i)=>({id:`r-${i}`,source:`n-${String(i%100).padStart(3,"0")}`,target:`n-${String((i*17+3)%100).padStart(3,"0")}`,type:"calls"}));const a=layoutDiagram(ir),b=layoutDiagram(ir);finite(a);expect(a.edges).toHaveLength(400);expect(a.geometryHash).toBe(b.geometryHash)});
 it("supports extremely wide sequence and tall disconnected diagrams",()=>{const seq=base("sequence");seq.nodes=Array.from({length:30},(_,i)=>({id:`p${i}`,type:"participant",label:`Participant ${i}`,metadata:{order:i}}));const sr=layoutDiagram(seq);finite(sr);expect(sr.width).toBeGreaterThan(5000);const arch=base("architecture");arch.nodes=Array.from({length:30},(_,i)=>({id:`n${i}`,type:"component",label:`N${i}`}));const ar=layoutDiagram(arch,{nodeGapX:0});finite(ar);expect(ar.height).toBeGreaterThan(1000)});
});