import {describe,expect,it,beforeAll,afterAll} from "vitest";import {spawnSync} from "node:child_process";import {mkdtemp,writeFile,readFile,rm,mkdir} from "node:fs/promises";import {tmpdir} from "node:os";import {join,resolve} from "node:path";
let dir="";const bin=resolve("packages/cli/src/bin.ts");const run=(a:string[])=>spawnSync(process.execPath,["--experimental-strip-types",bin,...a],{cwd:process.cwd(),encoding:"utf8",env:{...process.env,FAKE_API_KEY:"DO_NOT_LEAK_FAKE_SECRET"}});
const ir={version:"1.0",kind:"architecture",document:{title:"CLI 日本語"},nodes:[{id:"a",type:"external",label:"A"},{id:"b",type:"runtime",label:"B"}],relationships:[{id:"ab",source:"a",target:"b",type:"calls"}],boundaries:[],evidence:[],presentation:{}};
beforeAll(async()=>{dir=await mkdtemp(join(process.cwd(),".g11-"));await writeFile(join(dir,"ir.json"),JSON.stringify(ir));await writeFile(join(dir,"bad.json"),JSON.stringify({...ir,relationships:[{id:"bad",source:"missing",target:"b",type:"calls"}]}));await writeFile(join(dir,"before.json"),JSON.stringify(ir));await writeFile(join(dir,"after.json"),JSON.stringify({...ir,nodes:[...ir.nodes,{id:"c",type:"storage",label:"C"}],boundaries:[{id:"trust",type:"trust",label:"Trust",nodeIds:["b"]}]}));await writeFile(join(dir,"snapshot.json"),JSON.stringify({repository:"fixture/repo",commitSha:"deadbeef",files:[{path:"src/index.ts",blobSha:"blob1",contentHash:"hash1",content:'import x from "./x"; const password="DO_NOT_LEAK_FAKE_SECRET";'},{path:"src/x.ts",blobSha:"blob2",contentHash:"hash2",content:"export default 1"}]}))});afterAll(()=>rm(dir,{recursive:true,force:true}));
describe("G11 visual process boundary",()=>{
 it("qualifies help, invalid command, doctor, guide and examples",()=>{expect(run(["--help"]).status).toBe(0);expect(run(["--help"]).stdout).toContain("doctor");expect(run(["wat"]).status).not.toBe(0);for(const c of ["doctor","guide","examples"]){const x=run([c]);expect(x.status,c).toBe(0);expect(()=>JSON.parse(x.stdout)).not.toThrow()}});
 it("executes create and rejects empty create",()=>{expect(run(["create","Show how authentication works in my SaaS"]).status).toBe(0);expect(run(["create",""]).status).not.toBe(0)});
 it("executes analyze through G7 and redacts secret sentinels",()=>{const x=run(["analyze",join(dir,"snapshot.json")]);expect(x.status).toBe(0);expect(x.stdout).toContain("deadbeef");expect(x.stdout).not.toContain("DO_NOT_LEAK_FAKE_SECRET")});
 it("validates valid and invalid IR with exit codes",()=>{expect(run(["validate",join(dir,"ir.json")]).status).toBe(0);const x=run(["validate",join(dir,"bad.json")]);expect(x.status).not.toBe(0);expect(x.stdout).toContain("RELATION_TARGET_MISSING")});
 it("executes inspect render and preview",()=>{expect(run(["inspect",join(dir,"ir.json")]).status).toBe(0);const svg=join(dir,"out.svg"),html=join(dir,"out.html");expect(run(["render",join(dir,"ir.json"),svg]).status).toBe(0);expect(run(["preview",join(dir,"ir.json"),html]).status).toBe(0)});
 it("executes compare with changed semantic classes",()=>{const x=run(["compare",join(dir,"before.json"),join(dir,"after.json")]);expect(x.status).toBe(0);const j=JSON.parse(x.stdout);expect(j.delta.addedNodes).toContain("c");expect(j.delta.addedBoundaries).toContain("trust")});
 it("exports HTML SVG PNG WebP through G8",()=>{for(const f of ["html","svg","png","webp"]){const out=join(dir,"export."+f),x=run(["export",join(dir,"ir.json"),f,out]);expect(x.status,f+" "+x.stderr).toBe(0)}});
 it("verifies through authoritative verifier",()=>{const x=run(["verify",join(dir,"ir.json")]);expect(x.status).toBe(0);expect(JSON.parse(x.stdout).artifactErrors).toEqual([])});
 it("delivers through G9 and preserves LKG on invalid input",async()=>{const store=join(dir,"store");await mkdir(store);expect(run(["deliver",join(dir,"ir.json"),store,"diagram"]).status).toBe(0);const good=await readFile(join(store,"diagram.good.json"),"utf8");const bad=run(["deliver",join(dir,"bad.json"),store,"diagram"]);expect(bad.status).not.toBe(0);expect(await readFile(join(store,"diagram.good.json"),"utf8")).toBe(good)});
 it("rejects unsafe paths and never prints environment secret",()=>{const x=run(["validate","../outside.json"]);expect(x.status).not.toBe(0);expect(x.stderr+x.stdout).not.toContain("DO_NOT_LEAK_FAKE_SECRET")});
 it("supports per-command help without execution",()=>{for(const c of ["doctor","guide","create","analyze","validate","inspect","render","preview","deliver","compare","export","verify","examples"]){const x=run([c,"--help"]);expect(x.status,c).toBe(0);expect(x.stdout).toContain("visual "+c)}});
});
