import {describe,expect,it} from "vitest";
import {DOMParser} from "@xmldom/xmldom";
import type {DiagramIR,DiagramKind} from "@visual-architecture/ir";
import {layoutDiagram} from "@visual-architecture/layout";
import {renderDiagram,renderers,validateRenderResult,validateSvg} from "../src/index";

const base=(kind:DiagramKind):DiagramIR=>({version:"1.0",kind,document:{title:"Qualification",description:"G5 semantic SVG"},nodes:[],relationships:[],boundaries:[],evidence:[],presentation:{preset:"classic",theme:"light"}});
const xml=(s:string)=>{const d=new DOMParser().parseFromString(s,"image/svg+xml");expect(d.documentElement.tagName).toBe("svg");expect(d.getElementsByTagName("parsererror").length).toBe(0);return d};
const render=(ir:DiagramIR)=>{const l=layoutDiagram(ir),r=renderDiagram(ir,l);expect(validateRenderResult(r,ir.kind,l.geometryHash)).toEqual([]);xml(r.svg);return{l,r,d:xml(r.svg)}};
const by=(d:Document,attr:string,value?:string)=>Array.from(d.getElementsByTagName("*")).filter(x=>x.hasAttribute(attr)&&(value===undefined||x.getAttribute(attr)===value));

describe("G5 true model-specific rendering",()=>{
 it("registers five distinct semantic renderer strategies",()=>{expect(Object.keys(renderers).sort()).toEqual(["architecture","data-flow","lifecycle","sequence","workflow"]);expect(new Set(Object.values(renderers)).size).toBe(5)});
 it("renders architecture boundaries, nesting, storage, external systems and relationship hooks",()=>{const ir=base("architecture");ir.nodes=[{id:"api",type:"component",label:"API"},{id:"db",type:"store",label:"Primary Store"},{id:"ext",type:"external",label:"Payments"}];ir.relationships=[{id:"r1",source:"api",target:"db",type:"writes",label:"persist"},{id:"r2",source:"ext",target:"api",type:"calls"}];ir.boundaries=[{id:"inner",type:"trust",label:"Trusted",nodeIds:["api","db"]},{id:"outer",type:"boundary",label:"Platform",nodeIds:["ext"],boundaryIds:["inner"]}];const {d}=render(ir);expect(by(d,"data-boundary-id").length).toBe(2);expect(by(d,"data-boundary-type","trust").length).toBe(1);expect(by(d,"data-shape","store").length).toBe(1);expect(by(d,"data-shape","external").length).toBe(1);expect(by(d,"data-relation-id").length).toBe(2)});
 it("renders workflow lanes, phases, decision grammar and non-color main path semantics",()=>{const ir=base("workflow");ir.nodes=[{id:"s",type:"start",label:"Start",metadata:{lane:"Requester",phase:"Intake"}},{id:"d",type:"decision",label:"Approve?",metadata:{lane:"Reviewer",phase:"Review"}},{id:"e",type:"end",label:"Done",metadata:{lane:"Reviewer",phase:"Review"}}];ir.relationships=[{id:"a",source:"s",target:"d",type:"flow",metadata:{mainPath:true}},{id:"b",source:"d",target:"e",type:"flow",metadata:{mainPath:true}}];const {d}=render(ir);expect(by(d,"data-lane-id").length).toBe(2);expect(by(d,"data-phase-id").length).toBe(2);expect(by(d,"data-shape","diamond").length).toBe(1);expect(by(d,"data-main-path","true").length).toBe(2)});
 it("renders sequence participants, lifelines, messages, activations and segments in G4 temporal order",()=>{const ir=base("sequence");ir.nodes=[{id:"c",type:"participant",label:"Client",metadata:{order:1,activationStart:1,activationEnd:3}},{id:"a",type:"participant",label:"API",metadata:{order:2}}];ir.relationships=[{id:"m1",source:"c",target:"a",type:"message",label:"request",metadata:{order:1,segment:"request"}},{id:"m2",source:"a",target:"c",type:"reply",label:"response",metadata:{order:2,segment:"request"}}];const {l,d}=render(ir);expect(by(d,"data-lifeline-id").length).toBe(2);expect(by(d,"data-message-id").length).toBe(2);expect(by(d,"data-activation-id").length).toBe(1);expect(by(d,"data-segment-id").length).toBe(1);expect(l.edges[1]!.points[0]!.y).toBeGreaterThan(l.edges[0]!.points[0]!.y)});
 it("renders data-flow source/process/store/destination with distinct grammar and fan-in/fan-out",()=>{const ir=base("data-flow");ir.nodes=[{id:"src",type:"source",label:"Source"},{id:"p",type:"process",label:"Normalize"},{id:"db",type:"store",label:"Warehouse"},{id:"dst",type:"destination",label:"Consumer"}];ir.relationships=[{id:"f1",source:"src",target:"p",type:"flow"},{id:"f2",source:"p",target:"db",type:"flow"},{id:"f3",source:"p",target:"dst",type:"flow"},{id:"f4",source:"db",target:"dst",type:"flow"}];ir.boundaries=[{id:"stage",type:"stage",label:"Transform",nodeIds:["p","db"]}];const {d}=render(ir);for(const s of ["source","processor","store","destination"])expect(by(d,"data-shape",s).length).toBe(1);expect(by(d,"data-flow-id").length).toBe(4);expect(by(d,"data-boundary-id").length).toBe(1)});
 it("renders lifecycle lanes, terminal double outlines, retries and cancellation/failure/completion",()=>{const ir=base("lifecycle");ir.nodes=[{id:"s",type:"state",label:"START",metadata:{state:"START",lane:"Runtime"}},{id:"a",type:"state",label:"ACTIVE",metadata:{state:"ACTIVE",lane:"Runtime"}},{id:"f",type:"state",label:"FAILED",metadata:{state:"FAILED",lane:"Recovery"}},{id:"c",type:"state",label:"CANCELLED",metadata:{state:"CANCELLED",lane:"Recovery"}},{id:"d",type:"state",label:"COMPLETED",metadata:{state:"COMPLETED",lane:"Runtime"}}];ir.relationships=[{id:"go",source:"s",target:"a",type:"transition"},{id:"retry",source:"a",target:"a",type:"transition"},{id:"fail",source:"a",target:"f",type:"transition"},{id:"cancel",source:"a",target:"c",type:"transition"},{id:"done",source:"a",target:"d",type:"transition"}];const {d}=render(ir);expect(by(d,"data-lifecycle-lane","true").length).toBe(2);expect(by(d,"data-terminal","true").length).toBe(3);expect(by(d,"data-self-loop","true").length).toBe(1);expect(by(d,"data-transition-id").length).toBe(5)});
 it("uses deterministic tspans for multiline multilingual labels",()=>{const ir=base("architecture");ir.nodes=[{id:"i18n",type:"component",label:"English हिन्दी मराठी 中文 日本語 Español — extremely long technical identifier"}];const {l,d}=render(ir);expect(l.nodes[0]!.labelLines.length).toBeGreaterThan(1);expect(d.getElementsByTagName("tspan").length).toBeGreaterThan(1);expect(renderDiagram(ir,l).svg).toContain("हिन्दी")});
 it("presets and themes preserve semantic IDs and authoritative geometry",()=>{const ir=base("architecture");ir.nodes=[{id:"api",type:"component",label:"API"}];const l=layoutDiagram(ir),hash=l.geometryHash,svgs=[];for(const preset of ["classic","signal","blueprint","editorial"] as const){ir.presentation={preset,theme:preset==="signal"?"dark":"light"};const r=renderDiagram(ir,l);expect(r.geometryHash).toBe(hash);expect(r.svg).toContain('id="node-api"');svgs.push(r.svg)}expect(new Set(svgs).size).toBe(4)});
 it("renders deterministic legend from G4 geometry",()=>{const ir=base("architecture");ir.nodes=[{id:"a",type:"component",label:"A"},{id:"b",type:"store",label:"B"}];const {l,d}=render(ir);expect(l.legend).toBeDefined();expect(d.getElementById("legend")).not.toBeNull();expect(by(d,"data-semantic-role","legend").length).toBe(1)});
 it("keeps hostile authored content inert and XML-valid",()=>{const ir=base("architecture");ir.document.title='<script onload="x">';ir.nodes=[{id:'evil&quot; onclick=&quot;x',type:"component",label:`</text><foreignObject onload="x">javascript:alert(1)& "\u0001`}];const {r,d}=render(ir);expect(d.getElementsByTagName("script").length).toBe(0);expect(d.getElementsByTagName("foreignObject").length).toBe(0);expect(validateSvg(r.svg)).toEqual([]);expect(r.svg).toContain("&lt;foreignObject")});
 it("validator rejects actual active SVG attack surfaces",()=>{expect(validateSvg('<svg><script>x</script></svg>')).toContain("SVG_SCRIPT_FORBIDDEN");expect(validateSvg('<svg><foreignObject/></svg>')).toContain("SVG_FOREIGN_CONTENT_FORBIDDEN");expect(validateSvg('<svg><g onclick="x"/></svg>')).toContain("SVG_EVENT_HANDLER_FORBIDDEN");expect(validateSvg('<svg><a href="javascript:x"/></svg>')).toContain("SVG_UNSAFE_URL")});
 it("provides stable accessibility and inspection hooks",()=>{const ir=base("architecture");ir.nodes=[{id:"a",type:"component",label:"API"}];const {d}=render(ir);expect(d.documentElement.getAttribute("role")).toBe("img");expect(d.documentElement.getAttribute("aria-labelledby")).toBe("diagram-title diagram-desc");expect(by(d,"data-node-id","a")[0]?.getAttribute("aria-label")).toBe("API")});
 it("renders dense 100-node/400-relationship stress fixture deterministically",()=>{const ir=base("architecture");ir.nodes=Array.from({length:100},(_,i)=>({id:`n${i}`,type:i%5===0?"store":"component",label:`Node ${i} हिन्दी 中文`}));ir.relationships=Array.from({length:400},(_,i)=>({id:`r${i}`,source:`n${i%100}`,target:`n${(i*17+3)%100}`,type:"calls"}));const l=layoutDiagram(ir),a=renderDiagram(ir,l),b=renderDiagram(ir,l);expect(a.svg).toBe(b.svg);const d=xml(a.svg);expect(by(d,"data-node-id").length).toBe(100);expect(by(d,"data-relation-id").length).toBe(400)});
 it("renders wide sequence and tall graph fixtures without changing G4 bounds",()=>{const seq=base("sequence");seq.nodes=Array.from({length:12},(_,i)=>({id:`p${i}`,type:"participant",label:`Participant ${i}`,metadata:{order:i}}));seq.relationships=Array.from({length:20},(_,i)=>({id:`m${i}`,source:`p${i%12}`,target:`p${(i+1)%12}`,type:"message",metadata:{order:i+1}}));const sl=layoutDiagram(seq),sr=renderDiagram(seq,sl);expect(sr.svg).toContain(`viewBox="0 0 ${sl.width} ${sl.height}"`);expect(xml(sr.svg).getElementsByTagName("svg").length).toBe(1)});
});
