import type {DiagramIR} from "@visual-architecture/ir";import type {LayoutResult} from "@visual-architecture/layout";import {renderDiagram,validateSvg} from "@visual-architecture/renderer";import {createSelfContainedHtml} from "@visual-architecture/viewer-runtime";
export type ExportFormat="html"|"svg"|"png"|"webp";export interface ExportArtifact{format:ExportFormat;mimeType:string;bytes:Uint8Array;hash:string;geometryHash:string;width?:number;height?:number;filename?:string}
export interface ExportFailure{ok:false;code:"UNSUPPORTED_FORMAT"|"INVALID_DIMENSIONS"|"RESOURCE_LIMIT"|"RASTERIZATION_FAILED"|"MALFORMED_ARTIFACT"|"CLIPBOARD_UNAVAILABLE"|"SHARE_UNAVAILABLE";message:string}
export interface ExportSuccess{ok:true;artifact:ExportArtifact}
export interface Rasterizer{rasterize(svg:string,width:number,height:number,format:"png"|"webp",options?:{background:"transparent"|"opaque"}):Promise<Uint8Array>}
export interface ExportOptions{width?:number;height?:number;scale?:number;background?:"transparent"|"opaque";filename?:string}
const enc=new TextEncoder(),dec=new TextDecoder();const MAX_DIM=16384,MAX_PIXELS=100_000_000;
export function hashBytes(bytes:Uint8Array):string{let h=2166136261;for(const b of bytes){h^=b;h=Math.imul(h,16777619)}return(h>>>0).toString(16).padStart(8,"0")}
export function safeFilename(title:string,format:ExportFormat):string{let n=title.normalize("NFKC").replace(/[\u0000-\u001f\u007f]/g,"").replace(/[\\/:*?"<>|]/g,"-").replace(/\.\.+/g,"-").trim().replace(/^\.+|\.+$/g,"").slice(0,120);if(!n)n="diagram";return`${n}.${format}`}
const artifact=(format:ExportFormat,mimeType:string,bytes:Uint8Array,geometryHash:string,width?:number,height?:number,filename?:string):ExportArtifact=>({format,mimeType,bytes,hash:hashBytes(bytes),geometryHash,...(width?{width}:{}),...(height?{height}:{}),...(filename?{filename}:{})});
const dimensions=(l:LayoutResult,o:ExportOptions={})=>{const scale=o.scale??1,w=o.width??Math.round(l.width*scale),h=o.height??Math.round(l.height*scale);if(!Number.isFinite(w)||!Number.isFinite(h)||!Number.isFinite(scale)||w<=0||h<=0||scale<=0)return{error:"INVALID_DIMENSIONS" as const};if(w>MAX_DIM||h>MAX_DIM||w*h>MAX_PIXELS)return{error:"RESOURCE_LIMIT" as const};return{width:Math.round(w),height:Math.round(h)}};
export function exportSvg(ir:DiagramIR,layout:LayoutResult,o:ExportOptions={}):ExportArtifact{const r=renderDiagram(ir,layout),d=o.width!==undefined||o.height!==undefined||o.scale!==undefined?dimensions(layout,o):{width:layout.width,height:layout.height};if("error"in d)throw new Error(d.error);let svg=r.svg;if(d.width!==layout.width||d.height!==layout.height)svg=svg.replace("<svg ",`<svg width="${d.width}" height="${d.height}" `);return artifact("svg","image/svg+xml",enc.encode(svg),r.geometryHash,d.width,d.height,safeFilename(o.filename??ir.document.title,"svg"))}
export function exportHtml(ir:DiagramIR,layout:LayoutResult,o:ExportOptions={}):ExportArtifact{const d=o.width!==undefined||o.height!==undefined||o.scale!==undefined?dimensions(layout,o):{width:layout.width,height:layout.height};if("error"in d)throw new Error(d.error);return artifact("html","text/html;charset=utf-8",enc.encode(createSelfContainedHtml(ir,layout)),layout.geometryHash,d.width,d.height,safeFilename(o.filename??ir.document.title,"html"))}
export async function exportRaster(ir:DiagramIR,layout:LayoutResult,format:"png"|"webp",rasterizer:Rasterizer,o:ExportOptions={}):Promise<ExportArtifact>{const d=dimensions(layout,o);if("error"in d)throw new Error(d.error);const svg=dec.decode(exportSvg(ir,layout).bytes);const bytes=await rasterizer.rasterize(svg,d.width,d.height,format,{background:o.background??"opaque"});const a=artifact(format,format==="png"?"image/png":"image/webp",bytes,layout.geometryHash,d.width,d.height,safeFilename(o.filename??ir.document.title,format));const errors=validateExport(a);if(errors.length)throw new Error(`MALFORMED_ARTIFACT:${errors.join(",")}`);return a}
const u32be=(b:Uint8Array,o:number)=>((b[o]??0)<<24)|((b[o+1]??0)<<16)|((b[o+2]??0)<<8)|(b[o+3]??0);
export function rasterInfo(bytes:Uint8Array,format:"png"|"webp"):{width:number;height:number}|undefined{if(format==="png"){if(bytes.length<24||![137,80,78,71,13,10,26,10].every((v,i)=>bytes[i]===v))return;return{width:u32be(bytes,16)>>>0,height:u32be(bytes,20)>>>0}}if(bytes.length<30||dec.decode(bytes.slice(0,4))!=="RIFF"||dec.decode(bytes.slice(8,12))!=="WEBP")return;const type=dec.decode(bytes.slice(12,16));if(type==="VP8X")return{width:1+(bytes[24]!|(bytes[25]!<<8)|(bytes[26]!<<16)),height:1+(bytes[27]!|(bytes[28]!<<8)|(bytes[29]!<<16))};return undefined}
export function validateExport(a:ExportArtifact):string[]{const e:string[]=[];if(!a.bytes.length)e.push("EXPORT_EMPTY");if(a.hash!==hashBytes(a.bytes))e.push("EXPORT_HASH_MISMATCH");if(a.width!==undefined&&(!Number.isFinite(a.width)||a.width<=0))e.push("EXPORT_DIMENSIONS_INVALID");if(a.height!==undefined&&(!Number.isFinite(a.height)||a.height<=0))e.push("EXPORT_DIMENSIONS_INVALID");if(a.format==="svg"){const s=dec.decode(a.bytes);e.push(...validateSvg(s));if(!s.includes('xmlns="http://www.w3.org/2000/svg"'))e.push("EXPORT_SVG_NAMESPACE_MISSING");if(!/viewBox="0 0 [\d.]+ [\d.]+"/.test(s))e.push("EXPORT_SVG_VIEWBOX_INVALID")}if(a.format==="html"){const s=dec.decode(a.bytes);if(!s.startsWith("<!doctype html>"))e.push("EXPORT_HTML_INVALID");if(!s.includes("<svg"))e.push("EXPORT_HTML_SVG_MISSING");if(/<script[^>]+\bsrc\s*=|<link[^>]+\bhref\s*=/i.test(s))e.push("EXPORT_HTML_EXTERNAL_DEPENDENCY")}if(a.format==="png"||a.format==="webp"){const info=rasterInfo(a.bytes,a.format);if(!info)e.push(a.format==="png"?"EXPORT_PNG_INVALID":"EXPORT_WEBP_INVALID");else if(a.width&&a.height&&(info.width!==a.width||info.height!==a.height))e.push("EXPORT_RASTER_DIMENSION_MISMATCH")}return [...new Set(e)]}
export async function copyArtifact(a:ExportArtifact,clipboard:{writeText?(s:string):Promise<void>;write?(items:unknown[]):Promise<void>}):Promise<void>{if((a.format==="html"||a.format==="svg")&&clipboard.writeText)return clipboard.writeText(dec.decode(a.bytes));if(clipboard.write)return clipboard.write([{type:a.mimeType,bytes:a.bytes}]);throw new Error("CLIPBOARD_UNAVAILABLE")}
export function sharePayload(a:ExportArtifact,title="Visual Architecture"){return{title,files:[{name:a.filename??`diagram.${a.format}`,type:a.mimeType,bytes:a.bytes}]}}
export async function shareArtifact(a:ExportArtifact,share:((data:ReturnType<typeof sharePayload>)=>Promise<void>)|undefined,title="Visual Architecture"):Promise<void>{if(!share)throw new Error("SHARE_UNAVAILABLE");await share(sharePayload(a,title))}
export async function exportDiagram(args:{format:ExportFormat;document:DiagramIR;layout:LayoutResult;options?:ExportOptions;rasterizer?:Rasterizer}):Promise<ExportSuccess|ExportFailure>{try{const {format,document,layout,options={}}=args;if(!(["html","svg","png","webp"] as string[]).includes(format))return{ok:false,code:"UNSUPPORTED_FORMAT",message:"Unsupported export format"};let a:ExportArtifact;if(format==="svg")a=exportSvg(document,layout,options);else if(format==="html")a=exportHtml(document,layout,options);else{if(!args.rasterizer)return{ok:false,code:"RASTERIZATION_FAILED",message:"Rasterizer unavailable"};a=await exportRaster(document,layout,format,args.rasterizer,options)}const errors=validateExport(a);return errors.length?{ok:false,code:"MALFORMED_ARTIFACT",message:errors.join(",")}:{ok:true,artifact:a}}catch(e){const m=String((e as Error).message);if(m.includes("INVALID_DIMENSIONS"))return{ok:false,code:"INVALID_DIMENSIONS",message:m};if(m.includes("RESOURCE_LIMIT"))return{ok:false,code:"RESOURCE_LIMIT",message:m};return{ok:false,code:"RASTERIZATION_FAILED",message:m}}}
