import type {DiagramIR} from "@visual-architecture/ir";import type {LayoutResult} from "@visual-architecture/layout";import {renderDiagram,validateSvg} from "@visual-architecture/renderer";import {createSelfContainedHtml} from "@visual-architecture/viewer-runtime";
export type ExportFormat="html"|"svg"|"png"|"webp";
export interface ExportArtifact{format:ExportFormat;mimeType:string;bytes:Uint8Array;hash:string;geometryHash:string}
const enc=new TextEncoder();
export function hashBytes(bytes:Uint8Array):string{let h=2166136261;for(const b of bytes){h^=b;h=Math.imul(h,16777619)}return(h>>>0).toString(16).padStart(8,"0")}
const artifact=(format:ExportFormat,mimeType:string,bytes:Uint8Array,geometryHash:string):ExportArtifact=>({format,mimeType,bytes,hash:hashBytes(bytes),geometryHash});
export function exportSvg(ir:DiagramIR,layout:LayoutResult):ExportArtifact{const r=renderDiagram(ir,layout);return artifact("svg","image/svg+xml",enc.encode(r.svg),r.geometryHash)}
export function exportHtml(ir:DiagramIR,layout:LayoutResult):ExportArtifact{return artifact("html","text/html;charset=utf-8",enc.encode(createSelfContainedHtml(ir,layout)),layout.geometryHash)}
export interface Rasterizer{rasterize(svg:string,width:number,height:number,format:"png"|"webp"):Promise<Uint8Array>}
export async function exportRaster(ir:DiagramIR,layout:LayoutResult,format:"png"|"webp",rasterizer:Rasterizer):Promise<ExportArtifact>{const svg=new TextDecoder().decode(exportSvg(ir,layout).bytes);const bytes=await rasterizer.rasterize(svg,layout.width,layout.height,format);return artifact(format,format==="png"?"image/png":"image/webp",bytes,layout.geometryHash)}
export function validateExport(a:ExportArtifact):string[]{const e:string[]=[];if(!a.bytes.length)e.push("EXPORT_EMPTY");if(a.hash!==hashBytes(a.bytes))e.push("EXPORT_HASH_MISMATCH");if(a.format==="svg"){const s=new TextDecoder().decode(a.bytes);e.push(...validateSvg(s)}if(a.format==="html"){const s=new TextDecoder().decode(a.bytes);if(!s.startsWith("<!doctype html>"))e.push("EXPORT_HTML_INVALID");if(!s.includes("<svg"))e.push("EXPORT_HTML_SVG_MISSING")}return e}
export async function copyArtifact(a:ExportArtifact,clipboard:{writeText?(s:string):Promise<void>;write?(items:unknown[]):Promise<void>}):Promise<void>{if((a.format==="html"||a.format==="svg")&&clipboard.writeText)return clipboard.writeText(new TextDecoder().decode(a.bytes));if(clipboard.write)return clipboard.write([a]);throw new Error("CLIPBOARD_UNAVAILABLE")}
export async function shareArtifact(a:ExportArtifact,share:(data:{title:string;files:Array<{name:string;type:string;bytes:Uint8Array}>})=>Promise<void>,title="Visual Architecture"):Promise<void>{await share({title,files:[{name:`diagram.${a.format}`,type:a.mimeType,bytes:a.bytes}]})}
