#!/usr/bin/env node
import {readFile,writeFile,mkdir,rm,stat} from "node:fs/promises";import {resolve,relative,dirname} from "node:path";import {chromium} from "@playwright/test";
import {COMMANDS,runCommand,type Command} from "./index.ts";import type {DiagramIR} from "@visual-architecture/ir";import type {RepositorySnapshot} from "@visual-architecture/analyzer";import type {DeliveryStore} from "@visual-architecture/delivery";import type {ExportArtifact,Rasterizer} from "@visual-architecture/exporter";
const HELP="Usage: visual <command> [arguments]\nCommands: "+COMMANDS.join(", ")+"\nUse visual <command> --help for command guidance.\n";
const helps:Record<Command,string>={doctor:"visual doctor",guide:"visual guide",create:'visual create "<intent>"',analyze:"visual analyze <snapshot.json>",validate:"visual validate <ir.json>",inspect:"visual inspect <ir.json>",render:"visual render <ir.json> [output.svg]",preview:"visual preview <ir.json> [output.html]",deliver:"visual deliver <ir.json> <store-dir> [key]",compare:"visual compare <before.json> <after.json>",export:"visual export <ir.json> <html|svg|png|webp> <output>",verify:"visual verify <ir.json>",examples:"visual examples"};
const safe=(p:string)=>{const r=resolve(p),cwd=resolve(process.cwd()),rel=relative(cwd,r);if(rel.startsWith("..")||rel===".."||rel.startsWith("/")||rel.includes(".."+requireSep()))throw Error("PATH_OUTSIDE_WORKSPACE");return r};const requireSep=()=>process.platform==="win32"?"\\":"/";
const json=async<T>(p:string):Promise<T>=>JSON.parse(await readFile(safe(p),"utf8"));
const encode=(a:ExportArtifact)=>({...a,bytes:Buffer.from(a.bytes).toString("base64")});const decode=(a:any):ExportArtifact=>({...a,bytes:new Uint8Array(Buffer.from(a.bytes,"base64"))});
class FileStore implements DeliveryStore{private dir:string;constructor(dir:string){this.dir=dir}p(k:string,s:string){return safe(resolve(this.dir,k+"."+s+".json"))}async readGood(k:string){try{return decode(JSON.parse(await readFile(this.p(k,"good"),"utf8")))}catch{return undefined}}async writeCandidate(k:string,a:ExportArtifact){await mkdir(safe(this.dir),{recursive:true});await writeFile(this.p(k,"candidate"),JSON.stringify(encode(a)))}async readCandidate(k:string){try{return decode(JSON.parse(await readFile(this.p(k,"candidate"),"utf8")))}catch{return undefined}}async promoteCandidate(k:string){const a=await this.readCandidate(k);if(!a)throw Error("CANDIDATE_MISSING");await writeFile(this.p(k,"good"),JSON.stringify(encode(a)));await this.discardCandidate(k)}async discardCandidate(k:string){await rm(this.p(k,"candidate"),{force:true})}}
async function rasterizer():Promise<{r:Rasterizer;close:()=>Promise<void>}>{const browser=await chromium.launch({headless:true}),page=await browser.newPage();return{r:{rasterize:async(svg,w,h,format)=>{await page.setContent(`<!doctype html><style>html,body{margin:0}</style>${svg}`);await page.locator("svg").evaluate((e:any,d:any)=>{e.setAttribute("width",d.w);e.setAttribute("height",d.h)},{w,h});return new Uint8Array(await page.locator("svg").screenshot({type:format}))}},close:()=>browser.close()}}
async function main(){const args=process.argv.slice(2),raw=args[0];if(raw==="--help"||raw==="-h"){process.stdout.write(HELP);return}if(!raw||!COMMANDS.includes(raw as Command)){process.stderr.write(raw?"CLI_UNKNOWN_COMMAND\n"+HELP:HELP);process.exitCode=2;return}const cmd=raw as Command;if(args[1]==="--help"){process.stdout.write(helps[cmd]+"\n");return}try{let out:any;
 if(cmd==="doctor"||cmd==="guide"||cmd==="examples")out=await runCommand(cmd);
 else if(cmd==="create")out=await runCommand(cmd,{intent:args.slice(1).join(" ")});
 else if(cmd==="analyze")out=await runCommand(cmd,{snapshot:await json<RepositorySnapshot>(args[1]??"")});
 else if(cmd==="compare")out=await runCommand(cmd,{before:await json<DiagramIR>(args[1]??""),after:await json<DiagramIR>(args[2]??"")});
 else{const ir=await json<DiagramIR>(args[1]??"");if(cmd==="render"){out=await runCommand(cmd,{ir});if(args[2])await writeFile(safe(args[2]),out.svg)}
 else if(cmd==="preview"){out=await runCommand(cmd,{ir});if(args[2])await writeFile(safe(args[2]),out)}
 else if(cmd==="deliver"){const storeDir=args[2];if(!storeDir)throw Error("STORE_DIR_REQUIRED");out=await runCommand(cmd,{ir,deliveryStore:new FileStore(storeDir),deliveryKey:args[3]??"default"})}
 else if(cmd==="export"){const format=(args[2]??"html") as any,output=args[3];let rr:Awaited<ReturnType<typeof rasterizer>>|undefined;try{if(format==="png"||format==="webp")rr=await rasterizer();out=await runCommand(cmd,{ir,format,...(rr?{rasterizer:rr.r}:{})});if(!out.ok)throw Error(out.code);if(output)await writeFile(safe(output),out.artifact.bytes);out={...out,artifact:encode(out.artifact)}}finally{await rr?.close()}}
 else out=await runCommand(cmd,{ir})}
 if((cmd==="validate"&&out.valid===false)||(cmd==="analyze"&&out.ok===false)||(cmd==="deliver"&&out.accepted===false))process.exitCode=1;process.stdout.write(JSON.stringify(out,(k,v)=>v instanceof Uint8Array?Buffer.from(v).toString("base64"):v)+"\n");
 }catch(e){const m=e instanceof Error?e.message:String(e);process.stderr.write(m+"\n");process.exitCode=1}}
main();
