import {describe,expect,it} from "vitest";
import {chromium,type Page} from "@playwright/test";
import {readFile} from "node:fs/promises";
import type {DiagramIR} from "@visual-architecture/ir";
import {layoutDiagram} from "@visual-architecture/layout";
import {exportHtml,exportRaster,hashBytes,rasterInfo,validateExport,type ExportArtifact,type Rasterizer} from "@visual-architecture/exporter";

const ir:DiagramIR={version:"1.0",kind:"architecture",document:{title:"Offline G8"},nodes:[{id:"web",type:"external",label:"Web"},{id:"api",type:"runtime",label:"API"},{id:"db",type:"storage",label:"Database"}],relationships:[{id:"wa",source:"web",target:"api",type:"calls"},{id:"ad",source:"api",target:"db",type:"reads"}],boundaries:[{id:"trust",type:"trust",label:"Trust",nodeIds:["api","db"]}],evidence:[],presentation:{locale:"en"}};

async function rasterizer(page:Page):Promise<Rasterizer>{return{rasterize:async(svg,w,h,format)=>{await page.setContent(`<!doctype html><style>html,body{margin:0;width:${w}px;height:${h}px;background:white}</style>${svg}`);await page.locator("svg").evaluate((e:any,d:any)=>{e.setAttribute("width",d.w);e.setAttribute("height",d.h)},{w,h});return new Uint8Array(await page.locator("svg").screenshot({type:format}))}}}
async function pixelReceipt(page:Page,bytes:Uint8Array){return page.evaluate(async raw=>{const blob=new Blob([new Uint8Array(raw)]),bmp=await createImageBitmap(blob),c=document.createElement("canvas");c.width=bmp.width;c.height=bmp.height;const x=c.getContext("2d")!;x.drawImage(bmp,0,0);const d=x.getImageData(0,0,c.width,c.height).data,regions=[0,0,0],seen=new Set<string>();for(let y=0;y<c.height;y+=Math.max(1,Math.floor(c.height/80)))for(let xx=0;xx<c.width;xx+=Math.max(1,Math.floor(c.width/120))){const i=(y*c.width+xx)*4,key=d[i]!+","+d[i+1]!+","+d[i+2]!+","+d[i+3]!;seen.add(key);if(!(d[i]!>245&&d[i+1]!>245&&d[i+2]!>245)){const r=xx<c.width/3?0:xx>c.width*2/3?2:1;regions[r]=(regions[r]??0)+1}}return{width:c.width,height:c.height,colors:seen.size,regions}},Array.from(bytes))}
function wide():DiagramIR{return{version:"1.0",kind:"sequence",document:{title:"Wide"},nodes:Array.from({length:10},(_,i)=>({id:`p${i}`,type:"participant",label:`Participant ${i}`,metadata:{order:i}})),relationships:Array.from({length:9},(_,i)=>({id:`m${i}`,source:`p${i}`,target:`p${i+1}`,type:"message",label:`message ${i}`,metadata:{order:i}})),boundaries:[],evidence:[],presentation:{theme:"light"}}}
function tall():DiagramIR{return{version:"1.0",kind:"architecture",document:{title:"Tall"},nodes:Array.from({length:14},(_,i)=>({id:`n${i}`,type:i%3===0?"store":"component",label:`Tall node ${i}`})),relationships:[],boundaries:[],evidence:[],presentation:{theme:"light"}}}
function nested():DiagramIR{return{version:"1.0",kind:"architecture",document:{title:"Nested"},nodes:[{id:"a",type:"component",label:"Outer child"},{id:"b",type:"component",label:"Inner child"},{id:"c",type:"external",label:"External"}],relationships:[{id:"ab",source:"a",target:"b",type:"calls",label:"inside"},{id:"bc",source:"b",target:"c",type:"calls",label:"cross boundary"}],boundaries:[{id:"inner",type:"trust",label:"Inner boundary",nodeIds:["b"]},{id:"outer",type:"trust",label:"Outer boundary",nodeIds:["a"],boundaryIds:["inner"]}],evidence:[],presentation:{theme:"light"}}}

describe("G8 real Chromium export qualification",()=>{
 it("loads standalone HTML offline and preserves viewer interactions",async()=>{const html=new TextDecoder().decode(exportHtml(ir,layoutDiagram(ir)).bytes),browser=await chromium.launch({headless:true}),context=await browser.newContext({viewport:{width:1280,height:800}});const network:string[]=[];context.on("request",r=>{if(/^https?:/.test(r.url()))network.push(r.url())});const page=await context.newPage(),errors:string[]=[];page.on("console",m=>{if(m.type()==="error")errors.push(m.text())});page.on("pageerror",e=>errors.push(e.message));try{await page.setContent(html,{waitUntil:"load"});expect(await page.locator("#canvas > svg").count()).toBe(1);await page.locator('[data-action="zoom-in"]').click();await page.fill("#search","database");expect(await page.locator('[data-node-id="db"]').evaluate((e:any)=>e.classList.contains("highlight"))).toBe(true);await page.locator('#canvas [data-node-id="api"]').click();expect(await page.locator("#panel").textContent()).toContain("API");await page.selectOption("#lens","storage");await page.fill("#route-from","web");await page.fill("#route-to","db");await page.locator('[data-action="route"]').click();await page.locator('[data-theme="dark"]').click();await page.evaluate(()=>{location.hash="#node=api&lens=runtime"});await page.waitForTimeout(25);expect(await page.locator("#panel").textContent()).toContain("API");expect(errors).toEqual([]);expect(network).toEqual([])}finally{await browser.close()}},30000);

 it("downloads HTML SVG PNG and WebP from real viewer controls through the export bridge",async()=>{const hostile={...ir,document:{...ir.document,title:"../../evil/a\\b:\u0000日本語"}};const html=new TextDecoder().decode(exportHtml(hostile,layoutDiagram(hostile)).bytes),browser=await chromium.launch({headless:true}),page=await browser.newPage({acceptDownloads:true});try{await page.setContent(html);await page.evaluate(()=>{(window as any).__blobTypes=[];const orig=URL.createObjectURL.bind(URL);URL.createObjectURL=(b:any)=>{(window as any).__blobTypes.push(b.type);return orig(b)}});for(const format of ["html","svg","png","webp"] as const){const [download]=await Promise.all([page.waitForEvent("download"),page.locator(`[data-export="${format}"]`).click()]);const path=await download.path();expect(path).toBeTruthy();const bytes=new Uint8Array(await readFile(path!)),name=download.suggestedFilename();expect(bytes.length).toBeGreaterThan(100);expect(name).not.toMatch(/[\\/:]/);expect(name).toMatch(new RegExp("\\."+format+"$"));const mime=format==="html"?"text/html;charset=utf-8":format==="svg"?"image/svg+xml":format==="png"?"image/png":"image/webp";const a:ExportArtifact={format,mimeType:mime,bytes,hash:hashBytes(bytes),geometryHash:"download",...(format==="png"||format==="webp"?rasterInfo(bytes,format):{})};expect(validateExport(a)).toEqual([])}const types=await page.evaluate(()=>(window as any).__blobTypes);expect(types).toEqual(expect.arrayContaining(["text/html;charset=utf-8","image/svg+xml","image/png","image/webp"]))}finally{await browser.close()}},30000);

 it("decodes wide tall and nested PNG/WebP and proves distributed nonblank content without clipping",async()=>{const browser=await chromium.launch({headless:true}),page=await browser.newPage({viewport:{width:1280,height:900}});try{const r=await rasterizer(page);for(const fixture of [wide(),tall(),nested()]){const l=layoutDiagram(fixture);let prior:any;for(const format of ["png","webp"] as const){const a=await exportRaster(fixture,l,format,r),receipt=await pixelReceipt(page,a.bytes);expect(validateExport(a)).toEqual([]);expect(receipt.width).toBe(l.width);expect(receipt.height).toBe(l.height);expect(receipt.colors).toBeGreaterThan(3);expect(receipt.regions.reduce((x:number,y:number)=>x+y,0)).toBeGreaterThan(8);if(fixture.document.title==="Wide"){expect(receipt.regions[0]).toBeGreaterThan(0);expect(receipt.regions[1]).toBeGreaterThan(0);expect(receipt.regions[2]).toBeGreaterThan(0)}if(prior){expect(receipt.width).toBe(prior.width);expect(receipt.height).toBe(prior.height);expect(receipt.regions.map((n:number)=>n>0)).toEqual(prior.regions.map((n:number)=>n>0))}prior=receipt}}}finally{await browser.close()}},30000);

 it("keeps raster bytes free of controlled metadata sentinels and exercises clipboard/share capability boundaries",async()=>{const browser=await chromium.launch({headless:true}),page=await browser.newPage({viewport:{width:390,height:844},hasTouch:true,isMobile:true}),l=layoutDiagram(ir);try{const r=await rasterizer(page),sentinels=["DO_NOT_EXPORT_FAKE_API_KEY_123","ghp_FAKE_GITHUB_TOKEN_SENTINEL","/home/runner/work/SECRET_SENTINEL","/tmp/chromium-SECRET"];for(const f of ["png","webp"] as const){const a=await exportRaster(ir,l,f,r),raw=new TextDecoder().decode(a.bytes);for(const s of sentinels)expect(raw).not.toContain(s)}const caps=await page.evaluate(()=>({clipboard:!!navigator.clipboard,share:typeof navigator.share==="function"}));expect(typeof caps.clipboard).toBe("boolean");expect(typeof caps.share).toBe("boolean")}finally{await browser.close()}},30000);
});