import {describe,expect,it} from "vitest";import {chromium} from "@playwright/test";import type {DiagramIR,DiagramKind} from "@visual-architecture/ir";import {layoutDiagram} from "@visual-architecture/layout";import {copyArtifact,exportDiagram,exportHtml,exportRaster,exportSvg,rasterInfo,safeFilename,shareArtifact,sharePayload,validateExport,type Rasterizer} from "../src/index";
const kinds:DiagramKind[]=["architecture","workflow","sequence","data-flow","lifecycle"];
const mk=(kind:DiagramKind,label="API"):DiagramIR=>({version:"1.0",kind,document:{title:"Export / ../ नमस्ते 日本語",description:"Español मराठी 中文"},nodes:kind==="sequence"?[{id:"a",type:"participant",label},{id:"b",type:"participant",label:"Backend"}]:kind==="lifecycle"?[{id:"s",type:"state",label:"START",metadata:{state:"START"}},{id:"c",type:"state",label:"COMPLETED",metadata:{state:"COMPLETED"}}]:kind==="workflow"?[{id:"s",type:"start",label:"Start",metadata:{lane:"UI",phase:"Input"}},{id:"e",type:"end",label:"End",metadata:{lane:"API",phase:"Output"}}]:kind==="data-flow"?[{id:"s",type:"source",label},{id:"d",type:"store",label:"Store"}]:[{id:"api",type:"component",label},{id:"db",type:"store",label:"Database"}],relationships:kind==="sequence"?[{id:"m",source:"a",target:"b",type:"message",label:"request",metadata:{order:1}}]:kind==="lifecycle"?[{id:"t",source:"s",target:"c",type:"transition"},{id:"loop",source:"s",target:"s",type:"transition"}]:[{id:"r",source:kind==="workflow"?"s":kind==="data-flow"?"s":"api",target:kind==="workflow"?"e":kind==="data-flow"?"d":"db",type:kind==="data-flow"?"flow":"calls",label:"uses"}],boundaries:kind==="architecture"?[{id:"trust",type:"trust",label:"Boundary",nodeIds:["api","db"]}]:[],evidence:[],presentation:{theme:"light",locale:"en"}});
async function chromiumRasterizer():Promise<{r:Rasterizer;close:()=>Promise<void>}>{const browser=await chromium.launch({headless:true});return{close:()=>browser.close(),r:{rasterize:async(svg,w,h,format,options)=>{const page=await browser.newPage({viewport:{width:Math.max(1,w),height:Math.max(1,h)}});try{await page.setContent(`<!doctype html><style>html,body{margin:0;width:${w}px;height:${h}px;background:${options?.background==="transparent"?"transparent":"white"}}</style>${svg}`);const el=page.locator("svg");await el.evaluate((e:any,d:any)=>{e.setAttribute("width",d.w);e.setAttribute("height",d.h)},{w,h});return new Uint8Array(await el.screenshot({type:format,omitBackground:options?.background==="transparent"}))}finally{await page.close()}}}}}
describe("G8 real export",()=>{
 it("exports independently validated SVG and standalone HTML",()=>{const ir=mk("architecture"),l=layoutDiagram(ir);const s=exportSvg(ir,l),h=exportHtml(ir,l);expect(validateExport(s)).toEqual([]);expect(validateExport(h)).toEqual([]);expect(new TextDecoder().decode(s.bytes)).toContain('xmlns="http://www.w3.org/2000/svg"');expect(new TextDecoder().decode(h.bytes)).toContain("Interactive diagram")});
 it("rejects fake raster bytes",()=>{const ir=mk("architecture"),l=layoutDiagram(ir);const fake={format:"png" as const,mimeType:"image/png",bytes:new TextEncoder().encode("png:pixels"),hash:"",geometryHash:l.geometryHash};fake.hash=(awaitHash=>awaitHash)(fake.bytes.reduce((h,b)=>{h^=b;return Math.imul(h,16777619)},2166136261)>>>0).toString(16).padStart(8,"0");expect(validateExport(fake)).toContain("EXPORT_PNG_INVALID")});
 it("creates genuine PNG and WebP bytes in Chromium",async()=>{const x=await chromiumRasterizer();try{const ir=mk("architecture"),l=layoutDiagram(ir);for(const f of ["png","webp"] as const){const a=await exportRaster(ir,l,f,x.r);expect(validateExport(a)).toEqual([]);expect(rasterInfo(a.bytes,f)).toEqual({width:l.width,height:l.height})}}finally{await x.close()}},30000);
 it.each(kinds)("exports %s as SVG HTML PNG WebP",async kind=>{const x=await chromiumRasterizer();try{const ir=mk(kind),l=layoutDiagram(ir);expect(validateExport(exportSvg(ir,l))).toEqual([]);expect(validateExport(exportHtml(ir,l))).toEqual([]);for(const f of ["png","webp"] as const)expect(validateExport(await exportRaster(ir,l,f,x.r))).toEqual([])}finally{await x.close()}},30000);
 it.each(["English","हिन्दी","मराठी","中文","日本語","Español","Long label\nwith multiple lines and Unicode 日本語"])("preserves multilingual/multiline %s",label=>{const ir=mk("architecture",label),l=layoutDiagram(ir);expect(new TextDecoder().decode(exportSvg(ir,l).bytes)).toContain(label.includes("\n")?"Long label":label);expect(validateExport(exportHtml(ir,l))).toEqual([])});
 it("supports dark/light without semantic mutation",()=>{const a=mk("architecture");const dark:DiagramIR={...a,presentation:{...a.presentation,theme:"dark"}};const sa=new TextDecoder().decode(exportSvg(a,layoutDiagram(a)).bytes),sd=new TextDecoder().decode(exportSvg(dark,layoutDiagram(dark)).bytes);expect(sa).toContain("theme-light");expect(sd).toContain("theme-dark");expect(a.nodes.map(n=>n.id)).toEqual(dark.nodes.map(n=>n.id))});
 it("enforces dimensions and resource limits",async()=>{const ir=mk("architecture"),l=layoutDiagram(ir);expect((await exportDiagram({format:"png",document:ir,layout:l,options:{width:0}})).ok).toBe(false);const huge=await exportDiagram({format:"svg",document:ir,layout:l,options:{width:999999,height:999999}});expect(huge).toMatchObject({ok:false,code:"RESOURCE_LIMIT"})});
 it("sanitizes hostile filenames",()=>{const n=safeFilename("../a/b\\c:\u0000日本語","png");expect(n).not.toMatch(/[\\/:]/);expect(n.endsWith(".png")).toBe(true);expect(n.length).toBeLessThan(130)});
 it("keeps hostile authored content inert",()=>{const ir=mk("architecture",'<script>alert(1)</script><img onerror="x">javascript:');const svg=new TextDecoder().decode(exportSvg(ir,layoutDiagram(ir)).bytes);expect(svg).not.toContain("<script>alert");expect(svg).toContain("&lt;script&gt;");expect(validateExport(exportSvg(ir,layoutDiagram(ir)))).toEqual([])});
 it("qualifies clipboard success and unavailable paths",async()=>{const ir=mk("architecture"),a=exportSvg(ir,layoutDiagram(ir));let copied="";await copyArtifact(a,{writeText:async s=>{copied=s}});expect(copied).toContain("<svg");await expect(copyArtifact(a,{})).rejects.toThrow("CLIPBOARD_UNAVAILABLE")});
 it("qualifies share payload and unavailable path",async()=>{const ir=mk("architecture"),a=exportSvg(ir,layoutDiagram(ir));expect(sharePayload(a).files[0]!.type).toBe("image/svg+xml");let called=false;await shareArtifact(a,async()=>{called=true});expect(called).toBe(true);await expect(shareArtifact(a,undefined)).rejects.toThrow("SHARE_UNAVAILABLE")});
 it("rejects clipboard permission denial and unsupported MIME deterministically",async()=>{const ir=mk("architecture"),a=exportSvg(ir,layoutDiagram(ir));await expect(copyArtifact(a,{writeText:async()=>{throw new Error("NotAllowedError")}})).rejects.toThrow("CLIPBOARD_PERMISSION_DENIED");const forged={...a,mimeType:"application/x-hostile"};let touched=false;await expect(copyArtifact(forged,{write:async()=>{touched=true}})).rejects.toThrow("CLIPBOARD_MIME_UNSUPPORTED");expect(touched).toBe(false)});
 it("falsifies environment and path metadata leakage across text exports",()=>{const sentinels=["DO_NOT_EXPORT_FAKE_API_KEY_123","ghp_FAKE_GITHUB_TOKEN_SENTINEL","postgres://fake:password@secret/db","/home/runner/work/SECRET_SENTINEL","C:\\\\Users\\\\secret\\\\tmp","/tmp/chromium-SECRET","internal-candidate-SECRET.tmp"];const ir=mk("architecture"),l=layoutDiagram(ir);for(const a of [exportSvg(ir,l),exportHtml(ir,l)]){const text=new TextDecoder().decode(a.bytes);for(const s of sentinels)expect(text).not.toContain(s)}});
 it("exports a deterministic 100-node stress SVG without clipping bounds",()=>{const ir=mk("architecture");ir.nodes=Array.from({length:100},(_,i)=>({id:`n${i}`,type:i%5===0?"store":"component",label:`Node ${i}`}));ir.relationships=Array.from({length:99},(_,i)=>({id:`r${i}`,source:`n${i}`,target:`n${i+1}`,type:"calls"}));const l=layoutDiagram(ir),a=exportSvg(ir,l);expect(validateExport(a)).toEqual([]);expect(a.width).toBe(l.width);expect(a.height).toBe(l.height)});
});
