import {describe,expect,it} from "vitest";import {validateDiagramIR} from "@visual-architecture/validator";import {layoutDiagram} from "@visual-architecture/layout";import {renderDiagram,validateRenderResult} from "@visual-architecture/renderer";import {createSelfContainedHtml} from "@visual-architecture/viewer-runtime";import {analysisToArchitectureIR,analyzeRepository,assertReadOnlySnapshot,type RepositorySnapshot} from "../src/index";
const file=(path:string,content:string,hash="h")=>({path,content,blobSha:"blob-"+path,contentHash:hash});
const snap:RepositorySnapshot={repository:"acme/app",commitSha:"deadbeef",files:[
 file("src/server.ts",'import express from "express"; const auth=true; fetch("https://api.example");',"h1"),
 file("src/db.ts","const db = new PrismaClient();","h2"),file("package.json",'{"dependencies":{"express":"1.0.0","@acme/db":"workspace:*"},"devDependencies":{"vitest":"1"}}',"h3")
]};
describe("G7 repository intelligence",()=>{
 it("accepts pinned snapshots and rejects path/resource attacks",()=>{expect(assertReadOnlySnapshot(snap)).toEqual([]);expect(assertReadOnlySnapshot({...snap,files:[file("../secret","x","")]})).toEqual(expect.arrayContaining(["FILESYSTEM_ESCAPE","FILE_IDENTITY_MISSING"]));expect(assertReadOnlySnapshot({...snap,files:[file("deep.ts","x".repeat(1_000_001))]})).toContain("FILE_SIZE_LIMIT_EXCEEDED")});
 it("detects mixed languages and project boundaries deterministically",()=>{const s={...snap,files:[...snap.files,file("api/main.py","print('x')"),file("worker/main.go","package main"),file("core/src/lib.rs","fn x(){}"),file("java/src/App.java","class App{}"),file("api/pyproject.toml","[project]"),file("worker/go.mod","module x"),file("core/Cargo.toml","[package]"),file("java/pom.xml","<project/>")]};const a=analyzeRepository(s);expect(a.languages).toEqual(["Go","Java","Python","Rust","TypeScript"]);expect(a.projects.length).toBeGreaterThanOrEqual(5);expect(analyzeRepository({...s,files:[...s.files].reverse()})).toEqual(a)});
 it("separates runtime/dev dependencies and treats conventional entrypoints as inference",()=>{const a=analyzeRepository(snap);expect(a.dependencyRecords).toEqual(expect.arrayContaining([expect.objectContaining({name:"express",scope:"runtime"}),expect.objectContaining({name:"vitest",scope:"development"})]));expect(a.entryPoints.every(x=>x.classification==="INFERRED")).toBe(true)});
 it("ignores comments, generated and vendored code",()=>{const a=analyzeRepository({...snap,files:[...snap.files,file("src/comment.ts",'// fetch("https://evil")\n/* new PrismaClient() */'),{...file("dist/server.js",'fetch("x")'),generated:true},{...file("vendor/x.py","redis"),vendored:true}]});expect(a.runtime.filter(x=>/comment|dist|vendor/.test(x.source.file))).toEqual([])});
 it("reports malformed manifests rather than swallowing them",()=>expect(analyzeRepository({...snap,files:[file("package.json","{bad")]}).diagnostics.map(x=>x.code)).toContain("MALFORMED_MANIFEST"));
 it("redacts sensitive evidence and never executes repository text",()=>{(globalThis as any).__G7_PWNED=false;const a=analyzeRepository({...snap,files:[file("src/evil.ts",'const password=supersecret; globalThis.__G7_PWNED=true; fetch("x")')]});expect((globalThis as any).__G7_PWNED).toBe(false);expect(JSON.stringify(a)).not.toContain("supersecret")});
 it("redacts quoted secret values in evidence excerpts",()=>{const a=analyzeRepository({...snap,files:[file("src/index.ts",'import x from "./x"; const password="DO_NOT_LEAK_FAKE_SECRET";'),file("src/x.ts","export default 1")]});expect(JSON.stringify(a)).not.toContain("DO_NOT_LEAK_FAKE_SECRET");expect(JSON.stringify(a)).toContain("[REDACTED]")});
 it("keeps runtime/security static claims INFERRED even at high confidence",()=>{const a=analyzeRepository(snap);expect([...a.runtime,...a.security].every(x=>x.classification==="INFERRED")).toBe(true)});
 it("records exact non-first-line evidence ranges with CRLF and Unicode",()=>{const a=analyzeRepository({...snap,files:[file("src/server.ts",'// नमस्ते\r\nconst x=1;\r\nfetch("x");',"crlf")]});const r=a.runtime[0]!;expect(r.source.lineStart).toBe(3);expect(r.source.excerpt).toContain("fetch")});
 it("does not fabricate architecture relationships without edge evidence",()=>{const ir=analysisToArchitectureIR(snap,analyzeRepository(snap));expect(ir.relationships).toEqual([]);expect(ir.evidence.every(e=>e.commitSha==="deadbeef"&&e.blobSha&&e.contentHash)).toBe(true)});
 it("preserves VERIFIED import evidence separately from architectural runtime claims",()=>{const a=analyzeRepository({...snap,files:[...snap.files,file("src/a.ts",'import x from "./b";'),file("src/b.ts","export default 1")]});const rel=a.relationships.find(x=>x.label.includes("./b"))!;expect(rel.classification).toBe("VERIFIED");expect(rel.metadata?.relationType).toBe("imports")});
 it("excludes common generated/vendor directories",()=>{const a=analyzeRepository({...snap,files:[...snap.files,file("node_modules/x/index.js","fetch('x')"),file("coverage/a.js","redis")]});expect(a.runtime.some(x=>/node_modules|coverage/.test(x.source.file))).toBe(false)});
 it("reports sensitive-file handling and unsupported source honestly",()=>{const a=analyzeRepository({...snap,files:[...snap.files,file(".env","API_KEY=secret"),file("src/thing.swift","x")]});expect(a.diagnostics.map(x=>x.code)).toEqual(expect.arrayContaining(["SENSITIVE_FILE_REDACTED","UNSUPPORTED_LANGUAGE"]));expect(JSON.stringify(a)).not.toContain("API_KEY=secret")});
 it("proves repository → evidence → typed IR → validation → layout → render → viewer",()=>{const ir=analysisToArchitectureIR(snap,analyzeRepository(snap));const v=validateDiagramIR(ir);expect(v.valid).toBe(true);const g=layoutDiagram(ir);const rendered=renderDiagram(ir,g);expect(validateRenderResult(rendered,ir.kind,g.geometryHash)).toEqual([]);const html=createSelfContainedHtml(ir,g);expect(html).toContain("<!doctype html>");expect(html).toContain("deadbeef");expect(ir.evidence.length).toBeGreaterThan(0)});
});
